export enum QueryKey {
  GET_TEAMS = "GET_TEAMS",
  GET_TEAM_BY_SLUG = "GET_TEAM_BY_SLUG",
  GET_TEAM_BY_ID = "GET_TEAM_BY_ID",
  GET_TEAM_USERS_BY_TEAM_ID = "GET_TEAM_USERS_BY_TEAM_ID",
  GET_PRODUCTS = "GET_PRODUCTS",
  GET_CURRENT_USER = "GET_CURRENT_USER",
}
